language: python
python:
  - "3.7"
before_install:  
  - pip install --upgrade pip
matrix:
        include:
                - python: '3.7'
                  install:
                          - pip install -r requirements.txt
                          - pip install black
                  script:
                          - black --check wtrobot.py src/*.py
